on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing action'
        run: pwd

      - name: 'testing printing'
        run: acho reem
